# Generated by Django 3.0.9 on 2020-08-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='fips',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
