# Generated by Django 3.0.9 on 2020-08-24 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_source_fips'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedetail',
            name='last_pull',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_pull', to='sources.SourceDetail'),
        ),
    ]
