# Generated by Django 3.0.9 on 2020-08-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_sourcedetail_last_pull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcedetail',
            name='diff',
            field=models.TextField(blank=True, null=True),
        ),
    ]
