# Generated by Django 3.0.9 on 2020-08-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_auto_20200824_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcedetail',
            old_name='diff',
            new_name='html_diff',
        ),
        migrations.AddField(
            model_name='sourcedetail',
            name='text_diff',
            field=models.TextField(blank=True, null=True),
        ),
    ]
