# Generated by Django 3.0.9 on 2020-08-24 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_auto_20200824_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcedetail',
            name='last_pull',
        ),
        migrations.AddField(
            model_name='sourcedetail',
            name='previous_diff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_diff', to='sources.SourceDetail'),
        ),
    ]
