# Generated by Django 3.0.9 on 2020-08-24 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_auto_20200824_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedetail',
            name='next_diff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_prev_diff', to='sources.SourceDetail'),
        ),
        migrations.AlterField(
            model_name='sourcedetail',
            name='previous_diff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_next_diff', to='sources.SourceDetail'),
        ),
    ]
