# Generated by Django 3.0.9 on 2020-08-28 03:40

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0007_auto_20200824_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sourcedetail',
            name='date_pulled',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
