# Generated by Django 3.0.9 on 2020-08-28 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0008_alter_date_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcedetail',
            options={'ordering': ['-date_pulled']},
        ),
    ]
