# Generated by Django 3.0.9 on 2020-09-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0011_fips'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fips',
            options={'ordering': ['fips'], 'verbose_name_plural': 'Fips'},
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
