# Generated by Django 3.0.9 on 2020-09-03 02:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sources', '0012_auto_20200831_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='user_subscription',
            field=models.ManyToManyField(related_name='subscribed_diffs', to=settings.AUTH_USER_MODEL),
        ),
    ]
